# Generated by Django 4.2.5 on 2023-09-10 05:31

import ckeditor.fields
import core.utils.tools
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to=core.utils.tools.get_services_image)),
                ('price', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.CreateModel(
            name='AltServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to=core.utils.tools.get_services_image)),
                ('services', models.CharField(choices=[('hourly', 'Hourly Price'), ('standart', 'Standart Price')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_services', to='core.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'AltServices',
                'verbose_name_plural': 'AltServicess',
            },
        ),
    ]
