# Generated by Django 4.2.5 on 2023-09-10 05:42

import ckeditor.fields
import core.utils.tools
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_service_rename_isactive_blog_is_active_altservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('absheron', 'Absheron'), ('agjabadi', 'Aghjabadi'), ('agdam', 'Agdam'), ('agdash', 'Agdash'), ('agsu', 'Agsu'), ('shirvan', 'Shirvan'), ('astara', 'Astara'), ('baku', 'Baku'), ('balakan', 'Balakan'), ('barda', 'Barda'), ('beylagan', 'Beylagan'), ('bilasuvar', 'Bilasuvar'), ('jabrayil', 'Jabrayil'), ('jalilabad', 'Jalilabad'), ('dashkasan', 'Dashkasan'), ('shabran', 'Shabran'), ('fuzuli', 'Fuzuli'), ('gadabay', 'Gadabay'), ('ganja', 'Ganja'), ('goranboy', 'Goranboy'), ('goychay', 'Goychay'), ('hajigabul', 'Hajigabul'), ('imishli', 'Imishli'), ('ismayilli', 'Ismayilli'), ('kalbajar', 'Kalbajar'), ('kurdamir', 'Kurdamir'), ('lachin', 'Lachin'), ('lankaran', 'Lankaran'), ('lerik', 'Lerik'), ('masally', 'Masally'), ('mingachevir', 'Mingachevir'), ('naftalan', 'Naftalan'), ('neftchala', 'Neftchala'), ('oguz', 'Oghuz'), ('qabala', 'Qabala'), ('qakh', 'Qakh'), ('gobustan', 'Gobustan'), ('quba', 'Quba'), ('qubadli', 'Qubadli'), ('qusar', 'Qusar'), ('saatly', 'Saatly'), ('sabirabad', 'Sabirabad'), ('shaki', 'Shaki'), ('salyan', 'Salyan'), ('shamakhi', 'Shamakhi'), ('shamkir', 'Shamkir'), ('samukh', 'Samukh'), ('siyazan', 'Siyazan'), ('sumqayit', 'Sumqayit'), ('shusha', 'Shusha'), ('tovuz', 'Tovuz'), ('ujar', 'Ujar'), ('khankendi', 'Khankendi'), ('goygol', 'Goygol'), ('khizi', 'Khizi'), ('khojaly', 'Khojaly'), ('khojavend', 'Khojavend'), ('yardimli', 'Yardimli'), ('yevlakh', 'Yevlakh'), ('zaqatala', 'Zaqatala'), ('zardab', 'Zardab')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='ServiceChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Radio', 'Radio'), ('Checkbox', 'Checkbox'), ('Input', 'Input')], default='Radio', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('subService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='altservice_choce', to='core.altservices')),
            ],
            options={
                'verbose_name': 'ServiceChoice',
                'verbose_name_plural': 'ServiceChoices',
            },
        ),
        migrations.CreateModel(
            name='Pros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=core.utils.tools.get_services_image)),
                ('bio', ckeditor.fields.RichTextField()),
                ('completedTaskCount', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('city', models.ManyToManyField(blank=True, to='core.city')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pro',
                'verbose_name_plural': 'Pros',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField()),
                ('address', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('progress', 'Progress'), ('completed', 'Completed'), ('closed', 'Closed')], default='new', max_length=50)),
                ('detail', models.TextField()),
                ('totalAmount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='altservice_orders', to='core.altservices')),
                ('tasker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_orders', to='core.pros')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
