# Generated by Django 4.2.5 on 2023-09-10 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_city_servicechoices_pros_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tasker',
            new_name='pro',
        ),
        migrations.RenameField(
            model_name='pros',
            old_name='completedTaskCount',
            new_name='completedtasks',
        ),
    ]
